name: Auto Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Celeritas
        run: |
          sudo apt update
          sudo apt install git -y
          git clone https://git.taumc.org/embeddedt/celeritas.git

      - name: Get latest hash
        working-directory: ./celeritas
        run: echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV


      - name: Get previous hash
        run: echo "PREVIOUS_HASH=$(cat ./latest_commit)" >> $GITHUB_ENV

      - name: Check if new commits appear
        run: |
          if [[$COMMIT_HASH == $PREVIOUS_HASH]]; then
            echo "SHOULD_RUN=false" >> $GITHUB_ENV
          else
            echo "SHOULD_RUN=true" >> $GITHUB_ENV
          fi


  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [check]
    if: $SHOULD_RUN == 'true'
    steps:
      - name: Get latest describe
        working-directory: ./celeritas
        run: echo "LATEST_DESCRIBE=$(git describe --tags)" >> $GITHUB_ENV

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Get release body
        working-directory: ./celeritas
        run: echo "RELEASE_BODY=$(git rev-list $PREVIOUS_HASH..$COMMIT_HASH --pretty)" >> $GITHUB_ENV

      - name: Set up JDK 8
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Fix Gradle permission
        run: chmod +x ./celeritas/gradlew

      - name: Build Jars
        working-directory: ./celeritas
        run: ./gradlew -Ptarget_versions=1.12.2 packageJar

      - name: Update hash storage
        run: echo '$COMMIT_HASH' > ./latest_commit

      - name: Commit hash update
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: 'latest_commit'
          push: true
          tag: '$LATEST_DESCRIBE-$CURRENT_DATE'

      - name: Write release body file
        run: |
          echo "Built on commit: [link](https://git.taumc.org/embeddedt/celeritas/commit/$COMMIT_HASH)" >> body.txt
          echo >> body.txt
          echo "$RELEASE_BODY" >> body.txt

      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "build/libs/1.12.2/*"
          generateReleaseNotes: false
          bodyFile: "body.txt"
          tag: "$LATEST_DESCRIBE-$CURRENT_DATE"